import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "@react-pdf-viewer/core/lib/styles/index.css";
import "@react-pdf-viewer/zoom/lib/styles/index.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import './index.css';
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App />);
